package vista;

import java.util.Arrays;
import java.util.Collections;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ManejoDeCadena extends javax.swing.JFrame {

    String cadena1, cadena2;

    public ManejoDeCadena() {
        initComponents();
        this.setTitle("Funciones de las Cadenas- Java");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cadena1 = new javax.swing.JTextField();
        txt_cadena2 = new javax.swing.JTextField();
        txt_resultado = new javax.swing.JTextField();
        NUMERO = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        jBLimpiarCampos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_longitud_ = new javax.swing.JButton();
        btn_equalsCase_ = new javax.swing.JButton();
        btn_equals_ = new javax.swing.JButton();
        btn_comparete_ = new javax.swing.JButton();
        btn_compareto_Case_ = new javax.swing.JButton();
        btn_CHAR_AT_ = new javax.swing.JButton();
        btn_separador = new javax.swing.JButton();
        btn_valueof = new javax.swing.JButton();
        btn_concat = new javax.swing.JButton();
        btn_subString = new javax.swing.JButton();
        btn_indexOf = new javax.swing.JButton();
        btn_lastIndexOf = new javax.swing.JButton();
        btn_startsWiht = new javax.swing.JButton();
        btn_endsWith = new javax.swing.JButton();
        btn_replace = new javax.swing.JButton();
        btn_replaceAll = new javax.swing.JButton();
        btn_toUpperCase = new javax.swing.JButton();
        btn_toLoweCase = new javax.swing.JButton();
        btn_toCharArray = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la cadena", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADENA 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADENA 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESULTADO");

        txt_cadena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadena1ActionPerformed(evt);
            }
        });

        txt_cadena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadena2ActionPerformed(evt);
            }
        });

        NUMERO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NUMERO.setForeground(new java.awt.Color(255, 255, 255));
        NUMERO.setText("NUMERO");

        jBLimpiarCampos.setText("LIMPIAR CAMPOS");
        jBLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(NUMERO))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txt_numero)
                    .addComponent(txt_cadena2)
                    .addComponent(txt_cadena1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLimpiarCampos)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cadena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cadena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUMERO)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLimpiarCampos)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funciones de la cadena", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_longitud_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_longitud_.setText("LONGITUD");
        btn_longitud_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_longitud_ActionPerformed(evt);
            }
        });

        btn_equalsCase_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_equalsCase_.setText("EQUALS CASE");
        btn_equalsCase_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalsCase_ActionPerformed(evt);
            }
        });

        btn_equals_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_equals_.setText("EQUALS");
        btn_equals_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equals_ActionPerformed(evt);
            }
        });

        btn_comparete_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_comparete_.setText("COMPARETO");
        btn_comparete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comparete_ActionPerformed(evt);
            }
        });

        btn_compareto_Case_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_compareto_Case_.setText("COMPARETO CASE");
        btn_compareto_Case_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compareto_Case_ActionPerformed(evt);
            }
        });

        btn_CHAR_AT_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_CHAR_AT_.setText("CHAR AT");
        btn_CHAR_AT_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CHAR_AT_ActionPerformed(evt);
            }
        });

        btn_separador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_separador.setText("SEPARADOR");
        btn_separador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_separadorActionPerformed(evt);
            }
        });

        btn_valueof.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_valueof.setText("VALUEOF");
        btn_valueof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valueofActionPerformed(evt);
            }
        });

        btn_concat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_concat.setText("CONCAT");
        btn_concat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_concatActionPerformed(evt);
            }
        });

        btn_subString.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_subString.setText("SUBSTRING");
        btn_subString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subStringActionPerformed(evt);
            }
        });

        btn_indexOf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_indexOf.setText("INDEXOF");
        btn_indexOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_indexOfActionPerformed(evt);
            }
        });

        btn_lastIndexOf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_lastIndexOf.setText("LASTINDEXOF");
        btn_lastIndexOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastIndexOfActionPerformed(evt);
            }
        });

        btn_startsWiht.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_startsWiht.setText("STARTSWITH");
        btn_startsWiht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startsWihtActionPerformed(evt);
            }
        });

        btn_endsWith.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_endsWith.setText("ENDSWITH");
        btn_endsWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endsWithActionPerformed(evt);
            }
        });

        btn_replace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_replace.setText("REPLACE");
        btn_replace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_replaceActionPerformed(evt);
            }
        });

        btn_replaceAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_replaceAll.setText("REPLACEALL");
        btn_replaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_replaceAllActionPerformed(evt);
            }
        });

        btn_toUpperCase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_toUpperCase.setText("TOUPPERCASE");
        btn_toUpperCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toUpperCaseActionPerformed(evt);
            }
        });

        btn_toLoweCase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_toLoweCase.setText("TOLOWERCASE");
        btn_toLoweCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toLoweCaseActionPerformed(evt);
            }
        });

        btn_toCharArray.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_toCharArray.setText("TOCHARARRAY");
        btn_toCharArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toCharArrayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_toUpperCase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_toLoweCase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_toCharArray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_compareto_Case_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CHAR_AT_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_separador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_valueof))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_longitud_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_equals_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_equalsCase_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_comparete_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_concat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_subString)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_indexOf)
                        .addGap(18, 18, 18)
                        .addComponent(btn_lastIndexOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_startsWiht)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_endsWith)
                        .addGap(18, 18, 18)
                        .addComponent(btn_replace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_replaceAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_longitud_)
                    .addComponent(btn_equalsCase_)
                    .addComponent(btn_equals_)
                    .addComponent(btn_comparete_))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_compareto_Case_)
                    .addComponent(btn_CHAR_AT_)
                    .addComponent(btn_separador)
                    .addComponent(btn_valueof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_concat)
                    .addComponent(btn_subString)
                    .addComponent(btn_indexOf)
                    .addComponent(btn_lastIndexOf))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_startsWiht)
                    .addComponent(btn_endsWith)
                    .addComponent(btn_replace)
                    .addComponent(btn_replaceAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_toUpperCase)
                    .addComponent(btn_toLoweCase)
                    .addComponent(btn_toCharArray))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_equalsCase_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalsCase_ActionPerformed
        JOptionPane.showMessageDialog(this, "Compara dos strings para ver si "
                + "son iguales ignorando las diferencias entre mayúsculas y "
                + "minúsculas.");

        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();
        if (cadena1.equalsIgnoreCase(cadena2)) {
            JOptionPane.showMessageDialog(null, "SON IGUALES");
            txt_resultado.setText("SON IGUALES");
        } else {

            JOptionPane.showMessageDialog(null, "NO SON IGUALES");
            txt_resultado.setText("NO SON IGUALES");
        }
    }//GEN-LAST:event_btn_equalsCase_ActionPerformed

    private void txt_cadena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadena1ActionPerformed

    private void btn_longitud_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_longitud_ActionPerformed

        JOptionPane.showMessageDialog(this, "Esta función se usa para obtener "
                + "la longitud de una cadena Java. El método de longitud de "
                + "cadena devuelve la cantidad de caracteres escritos en la "
                + "Cadena.");

        cadena1 = txt_cadena1.getText();
        txt_resultado.setText("" + cadena1.length());
        JOptionPane.showMessageDialog(null, "La longitud de la cadena es: " + cadena1.length());
    }//GEN-LAST:event_btn_longitud_ActionPerformed

    private void btn_equals_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equals_ActionPerformed
        JOptionPane.showMessageDialog(this, "Compara la cadena de texto contra "
                + "un objeto. Devolverá true si las cadenas comparadas son "
                + "iguales. En caso contrario devolverá false.");

        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        if (cadena1.equals(cadena2)) {
            JOptionPane.showMessageDialog(null, "SON IGUALES");
            txt_resultado.setText("SON IGUALES");

        } else {
            JOptionPane.showMessageDialog(null, "NO SON IGUALES");
            txt_resultado.setText("NO SON IGUALES");
        }
    }//GEN-LAST:event_btn_equals_ActionPerformed

    private void btn_comparete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comparete_ActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        if (cadena1.compareTo(cadena2) == 0) {
            JOptionPane.showMessageDialog(null, "SON IGUALES");
            txt_resultado.setText("SON IGUALES");

        } else {
            JOptionPane.showMessageDialog(null, "NO SON IGUALES");
            txt_resultado.setText("NO SON IGUALES");

        }
    }//GEN-LAST:event_btn_comparete_ActionPerformed

    private void btn_compareto_Case_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compareto_Case_ActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        if (cadena1.compareToIgnoreCase(cadena2) == 0) {
            JOptionPane.showMessageDialog(null, "SON IGUALES");
            txt_resultado.setText("SON IGUALES");

        } else {
            JOptionPane.showMessageDialog(null, "NO SON IGUALES");
            txt_resultado.setText("NO SON IGUALES");

        }
    }//GEN-LAST:event_btn_compareto_Case_ActionPerformed

    private void btn_CHAR_AT_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CHAR_AT_ActionPerformed
        cadena1 = txt_cadena1.getText();
        int posicion = Integer.parseInt(txt_numero.getText());
        txt_resultado.setText("" + cadena1.charAt(posicion));
    }//GEN-LAST:event_btn_CHAR_AT_ActionPerformed

    private void btn_separadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_separadorActionPerformed
        cadena1 = txt_cadena1.getText();
        txt_resultado.setText("");

        for (int i = 0; i < cadena1.length(); i++) {
            txt_resultado.setText(txt_resultado.getText() + cadena1.charAt(i) + " ");

        }
    }//GEN-LAST:event_btn_separadorActionPerformed

    private void jBLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposActionPerformed
        txt_cadena1.setText("");
        txt_cadena2.setText("");
        txt_numero.setText("");
        txt_resultado.setText("");

    }//GEN-LAST:event_jBLimpiarCamposActionPerformed

    private void btn_valueofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valueofActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        int cambiarAString = Integer.parseInt(txt_numero.getText());

        txt_resultado.setText(String.valueOf(cambiarAString));


    }//GEN-LAST:event_btn_valueofActionPerformed

    private void txt_cadena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadena2ActionPerformed

    private void btn_concatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_concatActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText(cadena1 + " " + cadena2);
    }//GEN-LAST:event_btn_concatActionPerformed

    private void btn_subStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subStringActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText("Cadena 1: " + cadena1.substring(0, 1) + " " + "Cadena 2: " + cadena2.substring(0, 1));
    }//GEN-LAST:event_btn_subStringActionPerformed

    private void btn_indexOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_indexOfActionPerformed

        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        int posicion = cadena1.indexOf(cadena2);

        if (posicion != -1) {
            JOptionPane.showMessageDialog(null, "Palabra ingresada encontrada");
            txt_resultado.setText("La posicion ingresada de: " + cadena2 + " es " + posicion);
        } else {
            txt_resultado.setText("Palabra no encontrada");
        }


    }//GEN-LAST:event_btn_indexOfActionPerformed

    private void btn_lastIndexOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastIndexOfActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText("No da la ultima posicion de la cadena: " + cadena1.lastIndexOf(cadena2));
    }//GEN-LAST:event_btn_lastIndexOfActionPerformed

    private void btn_startsWihtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startsWihtActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        int posicion = Integer.parseInt(txt_numero.getText());

        if (cadena1.startsWith(cadena2, posicion)) {
            txt_resultado.setText("Palabra ingresada si inicia en el indice "
                    + "colocado");

        } else {
            txt_resultado.setText("Palabra no inicia en el indice colcoado");
        }

    }//GEN-LAST:event_btn_startsWihtActionPerformed

    private void btn_endsWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endsWithActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        if (cadena1.endsWith(cadena2)) {
            txt_resultado.setText("Palabra ingresada finaliza en la cadena");

        } else {
            txt_resultado.setText("Palabra no finaliza en la cadena");
        }
    }//GEN-LAST:event_btn_endsWithActionPerformed

    private void btn_replaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_replaceActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText(cadena1.replace(cadena1, cadena2));

    }//GEN-LAST:event_btn_replaceActionPerformed

    private void btn_replaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_replaceAllActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        String guardar = JOptionPane.showInputDialog("Ingrese nuevo caracter a "
                + "cambiar: ");

        txt_resultado.setText(cadena1.replaceAll(cadena2, guardar));
    }//GEN-LAST:event_btn_replaceAllActionPerformed

    private void btn_toUpperCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toUpperCaseActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText("Cadena 1: " + cadena1.toUpperCase() + " " + "Cadena 2: "
                + "" + cadena2.toUpperCase());

    }//GEN-LAST:event_btn_toUpperCaseActionPerformed

    private void btn_toLoweCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toLoweCaseActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        txt_resultado.setText("Cadena 1: " + cadena1.toLowerCase() + " " + "Cadena 2: "
                + "" + cadena2.toLowerCase());
    }//GEN-LAST:event_btn_toLoweCaseActionPerformed

    private void btn_toCharArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toCharArrayActionPerformed
        cadena1 = txt_cadena1.getText();
        cadena2 = txt_cadena2.getText();

        char charCadena[] = cadena1.toCharArray();

        txt_resultado.setText(Arrays.toString(charCadena));


    }//GEN-LAST:event_btn_toCharArrayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejoDeCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejoDeCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejoDeCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejoDeCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejoDeCadena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NUMERO;
    private javax.swing.JButton btn_CHAR_AT_;
    private javax.swing.JButton btn_comparete_;
    private javax.swing.JButton btn_compareto_Case_;
    private javax.swing.JButton btn_concat;
    private javax.swing.JButton btn_endsWith;
    private javax.swing.JButton btn_equalsCase_;
    private javax.swing.JButton btn_equals_;
    private javax.swing.JButton btn_indexOf;
    private javax.swing.JButton btn_lastIndexOf;
    private javax.swing.JButton btn_longitud_;
    private javax.swing.JButton btn_replace;
    private javax.swing.JButton btn_replaceAll;
    private javax.swing.JButton btn_separador;
    private javax.swing.JButton btn_startsWiht;
    private javax.swing.JButton btn_subString;
    private javax.swing.JButton btn_toCharArray;
    private javax.swing.JButton btn_toLoweCase;
    private javax.swing.JButton btn_toUpperCase;
    private javax.swing.JButton btn_valueof;
    private javax.swing.JButton jBLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_cadena1;
    private javax.swing.JTextField txt_cadena2;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_resultado;
    // End of variables declaration//GEN-END:variables
}
